- name: apt install influxdb
  apt: name=influxdb
  when: influxdb_use_apt

- name: Create download directory
  file: path="{{ download_tmp_dir }}" state=directory recurse=yes
  when: not influxdb_use_apt

- name: Fetch package
  get_url: url={{influxdb_deb_src_url}}/influxdb_{{ influxdb_version }}_amd64.deb
           dest={{ download_tmp_dir }}/influxdb_{{ influxdb_version }}_amd64.deb
  register: get_url_result
  until: get_url_result.state == 'file'
  retries: 5
  delay: 1
  when: not influxdb_use_apt

- name: Install package
  command: dpkg --skip-same-version -i {{ download_tmp_dir }}/influxdb_{{ influxdb_version }}_amd64.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  when: not influxdb_use_apt
